# Generated by Django 3.0.8 on 2020-07-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_auto_20200707_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=40, verbose_name='عنوان'),
        ),
    ]
