# Generated by Django 3.0.8 on 2020-07-08 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_auto_20200707_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, unique=True, verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
