# Generated by Django 3.0.8 on 2020-07-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_auto_20200715_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(null=True, upload_to='products/galleries/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.Product')),
            ],
            options={
                'verbose_name': 'تصاویر',
                'verbose_name_plural': 'تصویر',
            },
        ),
    ]
