# Generated by Django 3.0.8 on 2020-07-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0009_auto_20200718_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
