# Generated by Django 3.0.8 on 2020-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0010_auto_20200730_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
