# Generated by Django 3.0.8 on 2020-08-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0011_auto_20200801_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=200, verbose_name='آدرس ایمیل شما')),
                ('message', models.TextField(verbose_name='نظر شما')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.Product', verbose_name='محصول')),
            ],
        ),
    ]
