# Generated by Django 3.0.8 on 2020-08-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0012_productcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
