# Generated by Django 3.0.8 on 2020-08-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0013_auto_20200821_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
