# Generated by Django 3.0.8 on 2020-08-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_attrebute', '0001_initial'),
        ('eshop_products', '0014_auto_20200827_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(to='eshop_products_attrebute.ProductAttribute', verbose_name='مشخصات'),
        ),
    ]
