# Generated by Django 3.0.8 on 2020-10-26 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_products', '0015_product_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='آدرس ایمیل '),
        ),
    ]
