# Generated by Django 3.0.8 on 2020-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_attrebute', '0002_auto_20200827_1336'),
        ('eshop_products', '0017_auto_20201031_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_products_attrebute.ProductAttribute', verbose_name='مشخصات'),
        ),
    ]
