# Generated by Django 3.0.8 on 2020-10-31 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_attrebute', '0002_auto_20200827_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_products', '0018_auto_20201031_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, to='eshop_products_attrebute.ProductAttribute', verbose_name='مشخصات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
    ]
