# Generated by Django 3.0.8 on 2020-09-08 16:53

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favourite_products', '0002_auto_20200901_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
