# Generated by Django 3.0.8 on 2020-09-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favourite_products', '0003_myvideos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyVideos',
        ),
    ]
