# Generated by Django 3.0.8 on 2020-08-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس شرکت')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره ی تماس')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('about_us', models.TextField(verbose_name='درباره ی ما')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'بخش تنظیمات',
            },
        ),
    ]
