# Generated by Django 3.0.8 on 2020-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='اندازه')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
            ],
        ),
    ]
