# Generated by Django 3.0.8 on 2020-08-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_attrebute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'مشخصه', 'verbose_name_plural': 'مشخصات'},
        ),
    ]
