# Generated by Django 3.0.8 on 2020-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='ارسال شده / نشده'),
        ),
    ]
