# Generated by Django 3.0.8 on 2020-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0002_orderdetail_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(default='red', max_length=50, verbose_name='رنگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(default=2, max_length=10, verbose_name='سایز'),
            preserve_default=False,
        ),
    ]
